### ISSUE TITLE
skip non-attached TVs

### ISSUE THREAD

**Issue by mgraham** [BobRay/newspublisher#12]
We are using NewsPublisher to edit multiple resources.  Some of the resources use different templates, and the templates have access to different template variables.

In a nutshell, some resources will have access to the 'seokeywords'  TV, and some will not.

We're using a NewsPublisher snippet like this: 

[[!NewsPublisher?
&parentid=7
&show=`pagetitle,longtitle,introtext,published,content,seokeywords`
&template=`parent`
]]

Currently, this snippet fails on resources that does not have access to the "seokeywords" TV.

We would like to request an option that makes NewsPublisher simply skip the non-attached TVs.  That would allow us to use the same editing snippet call for multiple documents, and would simplify our site structure considerably.

Michael

**Comment by BobRay** [comment]
Fixed in a later version.
