### ISSUE TITLE
Problem with TVs and snippet tags

### ISSUE THREAD

**Issue by rainbowtiger** [BobRay/newspublisher#16]
If I have a snippet tag in a TV, and edit that TV with NewsPublisher, the field on the NP editing screen doesn't keep the snippet tag in there; it replaces it with the evaluated output of the snippet! So when you then save the resource, the TV gets saved with the snippet output embedded in it and the tag is gone. The snippet is evaluated BEFORE the texarea gets displayed on the editing screen, so it's not a problem with saving, but rather a problem with fetching and displaying the TV data in the textarea. (my TV is richtext; don't know if this would occur with other data types.)

**Comment by BobRay** [comment]
Fixed.
