### ISSUE TITLE
np_unauthorized_document

### ISSUE THREAD

**Issue by crimsonpixel** [BobRay/newspublisher#28]
Ok, I'm using pdoResources to call a bunch of news items that I want a user to be able edit with Newspublisher.

I have a chunk which incorporates the NpEditThisButton

<article class="news">

<h3>[[+pagetitle]]</h3>

[[+content]]
[[!NpEditThisButton?np_edit_id=`[[+id]]`]]
</article>

This shows a nice Edit button next to each news item, but I can only edit the last news item on the list, the rest redirect to the news editor page but have np_unauthorized_document message. 

I have checked the permissions and they are all the same for each news item. There is nothing in the logs and I can't seem to figure it out.  I've checked the np_id in the snippet properties and that is set correctly. 

I'm using Revo 2.2.3 and currently developing on MODX Cloud. 

Assistance please ;)

**Comment by BobRay** [comment]
FYI, I thing the parent issue is solved [here] (https://github.com/BobRay/newspublisher/commit/8b2aec1e31096be9fa278a3dafc1c892617b4f39)

**Comment by BobRay** [comment]
[Here] (https://github.com/BobRay/newspublisher/commit/28da46667eae0dee5e010e8f90baa3ada76c2aad) is a more secure fix for the np_unauthorized_document errror:
