### ISSUE TITLE
Cache Clear not working

### ISSUE THREAD

**Issue by garryn** [BobRay/newspublisher#30]
There is a bug in newspublisher.class.php (version 2.0.0.pl) that is preventing the cache clear from being carried out (and renders the Clear Cache property useless).

The value of _clearcache_ is used to set _$fields['syncsite']_ which is used by the resource processors to determine if a cache clear is required, however that value is unset before the processors are ran on:

https://github.com/BobRay/newspublisher/blob/master/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1725

**Comment by BobRay** [comment]
Let me know if this is still unfixed.
