### ISSUE TITLE
Make NewsPublisher work with the new TinyMCE RTE (theboxer's version)

### ISSUE THREAD

**Issue by boformer** [BobRay/newspublisher#34]
Right now it throws an error.

Here is a partial solution: http://forums.modx.com/thread/97500/make-tinymce-rte-work-with-newspublisher

**Comment by BobRay** [comment]
I'm going to try to make NP work with donshakespeare's wrapper and the CDN version of TinyMCE as soon as he adds some new file browser options.  Would that solve your issue?

**Comment by boformer** [comment]
Right now the wrapper seems to be buggy. But that would work if it gets fixed.

**Comment by BobRay** [comment]
I'm working on a new version that loads TinyMCE from CDN and uses the elFinder browser.
