### ISSUE TITLE
Unknown field in show property 

### ISSUE THREAD

**Issue by donShakespeare** [BobRay/newspublisher#37]
https://github.com/BobRay/newspublisher/blob/dev/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L981

Well done on the latest release @BobRay

One problem persists so far on all my servers:
The `rtrim` call is causing issues with all my normal settings
```
   public function displayForm($show) {
        $show = rtrim(',', $show); // ***
        $fields = explode(',',$show);
        ...
```
I use:
`$show = preg_replace('/\s*,\s*/', ',', $show);`
or
 `$show = implode(',', array_map('trim', explode(',', $show)));`

**Comment by BobRay** [comment]
I don't understand this. I added that line to strip any extra comma at the end of the &show property. That caused an empty entry in the $show array. The line was meant to *prevent* that error message. I don't believe either of your lines would handle an extra final comma. 

The weird thing is that the rtrim() line shouldn't do anything at all if there's no final comma.

Would you try this:

`$show = rtrim('\n ,", $show);`

(Note the space between the \n and the comma).

**Comment by BobRay** [comment]
OK, fixed. The only substantive change is in the newspublisher.class.php file.

[6a887af](https://github.com/BobRay/newspublisher/commit/6a887af637aea4d903962b22fa519a422e363c24)

**Comment by donShakespeare** [comment]
Great.
So I guess, no need to clean up user's potential name mistakes?

**Comment by BobRay** [comment]
Up to a point. In version 3.0.1 (should be available now), empty entries from comma-separated lists are ignored.
