### ISSUE TITLE
Unknown field in show property

### ISSUE THREAD

**Issue by EkoOne** [BobRay/newspublisher#38]
Duplicate of #37 

After upgrading NP to v3.0 I get the error: _Unknown field in show property:_ when editing a front-end page using TW (MagicPublisher). However, editing the same page from the Manager works perfectly.

The front-end worked fine under NP v2.1.0.

**Comment by BobRay** [comment]
Is there a comma or space at the end of your &show property in the NewsPublisher snippet tag?

**Comment by EkoOne** [comment]
I defined the &show property in a custom (MagicPublisher) pset but no, there is no comma or space.

**Comment by BobRay** [comment]
I'm an idiot. the arguments in that line (line 981 of the newspublisher class file) are backwards. 
It should be:

`$show = rtrim($show, ',' );`

**Comment by BobRay** [comment]
OK, fixed. The only substantive change is in the newspublisher.class.php file.

[https://github.com/BobRay/newspublisher/commit/6a887af637aea4d903962b22fa519a422e363c24](https://github.com/BobRay/newspublisher/commit/6a887af637aea4d903962b22fa519a422e363c24)

**Comment by EkoOne** [comment]
Works for me. Thanks Bob.
