### ISSUE TITLE
Media Source Id in tpl

### ISSUE THREAD

**Issue by donShakespeare** [BobRay/newspublisher#39]
A) #36 
Maybe it is better to not have `&media_source` parameter hard coded in the class file. 
The TPL files can have it instead. Like:
`$PHs['[[+media_source]]'] = $mediaSourceId;`
Instead of:
`$PHs['[[+media_source]]'] = '?&media_source=' . $mediaSourceId;`
https://github.com/BobRay/newspublisher/blob/dev/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1716
https://github.com/BobRay/newspublisher/blob/dev/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1876

Right now, I can work with this, but one will have to use JS or other to strip everything but the number.
Also, is `?&` an error?

B) `[[+media_source]]` will return `0` if TV does not have an actively associated Media Source. But native MODX behaviour is to always assign some default TV (Filesystem)
Is this normal?

**Comment by donShakespeare** [comment]
After further investigation, NP will throw an error if the user does not associate a Media Source to TV. If you want the Default Source, you have to go to said TV and actively select the default and hit save
![image](https://cloud.githubusercontent.com/assets/5103329/23720465/fb3dd482-03fb-11e7-9bd1-54c305673c16.png)

https://github.com/BobRay/newspublisher/blob/dev/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1722

**Comment by donShakespeare** [comment]
This is what I am using to prevent `0`. Though I am not sure the way I am using `getOption` will accommodate the usergroup setting
https://github.com/BobRay/newspublisher/blob/6a887af637aea4d903962b22fa519a422e363c24/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1570
```
            case 'image':
            case 'file':
                // $mediaSourceId = $tv->get('source');
                $mediaSourceId = $tv->get('source') ?: $this->modx->getOption('default_media_source');
                $formTpl .= $this->_displayFileInput($name, $tvType.'Tpl', $mediaSourceId);
                break;
```
and
https://github.com/BobRay/newspublisher/blob/6a887af637aea4d903962b22fa519a422e363c24/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1460
```
            case 'richtext':
                $mediaSourceId = $tv->get('source') ?: $this->modx->getOption('default_media_source');
                $formTpl .= $this->_displayTextarea($name, false, 'richtext', 20, 60, $mediaSourceId);
                break;
```

**Comment by BobRay** [comment]
I understand the issue, but how can you get a TV with no Media Source (short of editing the DB)? Whenever I create one, it gets the default Media Source in its 'source' field. Even if I set it to 0 in the DB, the default Media Source comes back when I save it.

I avoided using the default Media Source, thinking that naive users would often be giving browsing access to their entire site (including config.inc.php). That's why I created the browserBasePath and browserBaseURL (defaulting to assets/) to use when no Media Source was set. Using that for TVs with no Media Source is pretty ugly, though, when doing the thumbnails for image TVs in NP.

I can do the code, but I'm not sure about the best way to solve this. Using the default_media_source setting is really easy, but the security vulnerability is pretty severe.

**Comment by donShakespeare** [comment]
> but how can you get a TV with no Media Source (short of editing the DB)? Whenever I create one, it gets the default Media Source in its 'source' field. Even if I set it to 0 in the DB, the default Media Source comes back when I save it.

All of this is absolutely true, only and only if you do not create the TV via **Quick Create**.
Also, if you **Quick Update** and save said quick-created TV (which has never been opened or saved in its own full page before), it will never receive a Media Source Id in the  `modx_media_sources_elements` table.

I am sure this is a bug and not peculiar to my environment; I will go find out from other users.
For now, I will tell users to not Quick Create their TVs.

>Using the default_media_source setting is really easy, but the security vulnerability is pretty severe.

I think you are on point concerning the inadvertent security hole this would cause.

**Comment by BobRay** [comment]
Let me know if my changes (dev branch) have fixed the problem with the Quick Update TVs. If so, I'll go to work on a System Setting to configure the name of the media_source $_GET variable.

**Comment by donShakespeare** [comment]
No, the problem persists.

**Comment by donShakespeare** [comment]
https://github.com/BobRay/newspublisher/blob/38f966bcddd765233fd74a41ee2bc9ace29b8c30/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1720
 
`$msVar = $this->modx->getOption('np_media_source_var', $this->props, 'media_source', true);`

What is `np_media_source_var` ?

**Comment by BobRay** [comment]
np_media_source_var is a new System Setting holding the name of the $_GET variable used to send the Media Source to the connector. I also removed the extraneous & sign. 

I'll take another look at the Quick Update issue.

**Comment by donShakespeare** [comment]
As for using the supplied media source tag in `npImageTpl` in JS. I came up with this method to extract the id from the string. This enables my custom media sources to sort themselves out regarding source/path.
```
<button id="np-[[+npx.fieldName]]_button" [[+media_source]] type="button" onclick="autoFileBrowser('np-[[+npx.fieldName]]','', '', '', '', $(this).attr('?media_source'))">Select an image</button>
```
Which translates to e.g
```
<button id="np-TinymceWrapperImageTV6_button" ?media_source="4" type="button" onclick="autoFileBrowser('np-TinymceWrapperImageTV6','', '', '', '', $(this).attr('?media_source'))">Select an image</button>
```

**Comment by BobRay** [comment]
I believe this is fixed. Let me know if it's not.
