### ISSUE TITLE
Unable to turn off RTE with `&initrte=0`

### ISSUE THREAD

**Issue by donShakespeare** [BobRay/newspublisher#40]
Set `&initrte=0` and you get this error for every rich field, introtext, desc, content, rich TVs

`The &initrte parameter is not set, but you asked for this richtext field: exampleTV`

I am currently coping by ditching the `else` statement
https://github.com/BobRay/newspublisher/blob/dev/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1880
```
                // $msg = $this->modx->lexicon('np_no_rte');
                // $this->setError($msg . $name);
                // $this->setFieldError($name, $msg);
                // $PHs['[[+npx.class]]'] = $noRTE_class;
```

**Comment by BobRay** [comment]
Maybe I'm misunderstanding you, but my assumption was that if you have a richtext item in the &show property or set introtext, content, or description to richtext, it's an error not to set &initrte to `1`.

I've thought about initializing the rte automatically in those cases, but the structure of NP makes it very difficult.

**Comment by donShakespeare** [comment]
>if you have a richtext item in the &show property or set introtext, content, or description to richtext, it's an error not to set &initrte to 1.
It would be an error only if the user definitely wanted to use the accompanying RTE settings and did not set `initrte` to true.

Take TinyMagicPublisher which uses NewsPublisher forms. It totally depends on NP except in the area of Rich Text Editing, since TMP uses true in-place inline editing - no textareas, or iframes.

Another example of two-step verification is the MODX Manager resource settings.
One is able to have that RichText box checked, and as many Rich TVs as possible, and still have no RTE initiated, because user has disabled `which_editor` ("None")

In NP, this will enable the user to utilize other solution in the way of RTEs and Code Editors.


>I've thought about initializing the rte automatically in those cases, but the structure of NP makes it very difficult.

I suggest to reinstate `which_editor` which was kinda in the previous major release.
https://github.com/BobRay/newspublisher/blob/76037a30ff4436c5f0dd8cd45d03f6b5ee948d71/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L546

But another setting name other than `which_editor` might be more suitable and appropriate, like `use_editor` or `use_tinymce` etc

So, in this new NP case we'll have something like
```
$this->use_tinymce = $this->modx->getOption('use_tinymce', $this->props, true, true); 
//which defaults to true
```
and then 
`        if ($RichText && $this->use_tinymce ) {`
https://github.com/BobRay/newspublisher/blob/6a887af637aea4d903962b22fa519a422e363c24/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1868

**Comment by BobRay** [comment]
OK, got it. I think I'll bring back the which_editor setting and just hide the error messages if it's set to 'none.' Does that sound good?

**Comment by donShakespeare** [comment]
A world of good. Triple cheers!

**Comment by BobRay** [comment]
Changed my mind on this. The property is called stopOnNoRte to parallel stopOnBadTV.  Set it to false to hide the errors. (See the dev branch).

**Comment by donShakespeare** [comment]
Works very nicely!

**Comment by BobRay** [comment]
Glad to hear it.
