### ISSUE TITLE
seems browserStartPath does not work

### ISSUE THREAD

**Issue by krava77** [BobRay/newspublisher#41]
Hello,
I need to show for users only their personal directory.
here is my npElFinderConnector code:
```
[[!npElFinderConnector?
    &browserStartPath=`[[++base_url]]assets/upload/[[!+modx.user.id]]/`
    &browserStartURL=`[[++base_url]]assets/upload/[[!+modx.user.id]]/`
    &disableCommands=`archive, download, cut, copy, paste, open, duplicate, edit, mkdir, mkfile, netmount, netunmount, quicklook, view `
    &uploadAllow=`image`
    &uploadMaxSize=`200K`
]]
```
but I still see modx root directory, when open npElFinder. Could you check it?
the path ( /assets/upload/1/ ) is correct and available on the server.

**Comment by BobRay** [comment]
Your browserStartPath has a URL in it, rather than a path. Try this: 

&browserStartPath=`[[++base_path]]assets/upload/[[!+modx.user.id]]/`

Also, it may be that calling the modx.user.id tag uncached delays its processing until after the outer tag is processed.

**Comment by krava77** [comment]
Thanks for the answer Bob. I changes browserStartPath as you described, but no luck. I tried to add direct path(/server-path-to-modx/assets/upload/2/) to  browserStartPath, but I have the same issue.
Also the "Pre-process tags in Property Values" checkbox is checked.
Any ideas how to resolve it?
BTW.  Seems browserStartURL does not use anywhere in the component code.

**Comment by krava77** [comment]
I've solved this issue. I added following code to the npElFinderContent chunk:
`useBrowserHistory : false,
customData : {path : getQueryVariable("path")},`
Here is solution:
https://github.com/Studio-42/elFinder/issues/356#issuecomment-34403463

**Comment by BobRay** [comment]
I'm glad you go that sorted. Thanks for reporting back.

It sounds like a bug in elFinder, which should normalize the path before checking for the substring.

**Comment by BobRay** [comment]
BTW, where exactly did you put that code?

**Comment by krava77** [comment]
After rememberLastDir
![image](https://cloud.githubusercontent.com/assets/784804/25046627/29091d7a-213b-11e7-8315-8435a6950cab.png)
