### ISSUE TITLE
Incorrect context

### ISSUE THREAD

**Issue by nafem** [BobRay/newspublisher#42]
Within a multi context environment, the context for new documents is always 'web'. The parent is set correctly but the context should be set the same as the parent.

**Comment by BobRay** [comment]
I think the latest commit for the dev branch fixes this. All you need is the [NewsPublisher class file](https://github.com/BobRay/newspublisher/blob/dev/core/components/newspublisher/model/newspublisher/newspublisher.class.php). Let me know if there's still a problem.

BTW, I'm working on a new version of SiteCheck which will repair the incorrect class_key fields.

**Comment by nafem** [comment]
Thanks Bob, that works correctly now.
