### ISSUE TITLE
How to resolve Conflict of elFinder search url parameter and MODX' q

### ISSUE THREAD

**Issue by donShakespeare** [BobRay/newspublisher#43]
https://github.com/Studio-42/elFinder/issues/1963#issuecomment-293956546

**Comment by BobRay** [comment]
I'm afraid I don't understand this issue. Can you fill me in?

**Comment by donShakespeare** [comment]
MODX hijacks the `&q` parameter for his htaccess redirecting and whatnot - how presumptuous of it.
Although the `request_parameter_alias` can be changed from `q` in system settings, I suggest MODX use something more proprietary as default, like `q_modx`, but until then ...

If you do directly `myMODXresource.html?q=exampleETC` you get a `404` page

Well, if your elFinder connector is a MODX resource...
and one were to do a search in elFinder for an item using  the `enter` key for a thorough search,
the search query is `appended` /  `posted to` the elFinder connector resource in this familiar fashion ...
 `myELFINDERconnector.html?q=exampleETC` 
By the time MODX renders that page in the backend, a `404` error would be tossed back and the elFinder search would invariably fail.

Solution: one could change MODX' behaviour, or elFinder's.
Since it is easier to let users not meddle with their existing MODX setup I'd go with fixing elFinder's request procedure

**Comment by BobRay** [comment]
Done (I hope).  `https://github.com/BobRay/newspublisher/commit/0a3d908e27fdd50a8747453cb383cb475e8b706c`

**Comment by donShakespeare** [comment]
Yup, that should do it.
