### ISSUE TITLE
npelfinderconnector html extension

### ISSUE THREAD

**Issue by chocolatkey** [BobRay/newspublisher#44]
npelfindercontent.chunk.tpl line 45 is url: "'[[++site_url]]npelfinderconnector.**html**[[+media_source]]',". The issue is if you have another file extension (or none at all) set for html documents:
![image](https://cloud.githubusercontent.com/assets/13407784/25483831/c378eaa4-2b57-11e7-8414-b0f5dcd54b0d.png)

then npelfinderconnector does not load because the extension is hard-coded.

**Comment by BobRay** [comment]
Thanks. I'll have to think about the best way to fix that.

**Comment by BobRay** [comment]
This should be fixed in the new version (3.0.3-pl).
