### ISSUE TITLE
Wishlist #1

### ISSUE THREAD

**Issue by TITAN-UZ** [BobRay/newspublisher#46]
Hi Bob
Add these parameters: 
1.  Add news section Tikets 
[URL=http://vfl.ru/fotos/838f16bd17476997.html]

2. Choice when you upgrade change the template (update re again will fix the templates)

**Comment by TITAN-UZ** [comment]
[URL=http://vfl.ru/fotos/838f16bd17476997.html][IMG]http://images.vfl.ru/ii/1496691537/838f16bd/17476997_s.png[/IMG][/URL]

**Comment by BobRay** [comment]
Sorry, I have no idea what you're suggesting. Those three fields should already be available in NewsPublisher if you put them in the &show property.

**Comment by TITAN-UZ** [comment]
&classkey=`Ticket` not working

**Comment by BobRay** [comment]
Try:

 &classkey=`Ticket`

If that doesn't work, are you seeing an error message? If so, paste it here.

**Comment by TITAN-UZ** [comment]
calling code on the page `		[[!NewsPublisher? 
			&show=`pagetitle,parent,template,introtext,content,published`
			&required=`pagetitle,content,parent,introtext`
			&initrte=`1`
			&parentid=`4`
			&rtcontent=`1`
			&parents=`4`
			&published=`1`
			&templates =`3,4,10`
			&textmaxlength =`255`
			&initfilebrowser=`1`
			&classkey=`Ticket`
		]]`

Error when calling and adding

`[2017-06-07 16:57:57] (ERROR @ **********/xpdoobject.class.php : 1452) Error 23000 executing statement:
INSERT INTO `modx_tickets_totals` (`class`, `tickets`, `comments`, `views`, `stars`, `rating`, `rating_plus`, `rating_minus`) VALUES ('Ticket', 0, 0, 0, 0, 0, 0, 0)
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '0-Ticket' for key 'PRIMARY'
)
`

**Comment by BobRay** [comment]
Does the Ticket class extend modResource?  If not, what MOPDX class does it extend?

**Comment by TITAN-UZ** [comment]
Yes expand! https://github.com/bezumkin/Tickets/blob/master/core/components/tickets/model/tickets/ticketssection.class.php

**Comment by TITAN-UZ** [comment]
https://github.com/bezumkin/Tickets/blob/master/core/components/tickets/model/tickets/tickets.class.php

**Comment by BobRay** [comment]
No, the TicketsSection class extends modResource.

The Tickets class extends nothing, so it's not going to work as a document or in NP.
