### ISSUE TITLE
Configuring parent

### ISSUE THREAD

**Issue by markschl** [BobRay/newspublisher#47]
After updating to the Newspublisher 3, which added some nice features I noticed that I cannot find a way to add child resources to many different pages like I had previously done using some custom code that was too laborious to maintain.
Each of these container pages has a "Create article" button on it which redirects to the Newspublisher page. However, how can I tell Newspublisher that the new resource should accept the previous container page to be its parent? I tried forwarding the ID as URL parameter and adding this to Newspublisher:

`&parentid='[[!getUrlParam?name='parentid']]'`

However, the parentid will be forgotten on the postback page when the form is saved. Is there any smart possibility that I can't think of? If not, it might be a nice feature to have a "CreateButton" snippet wich automatically checks the permissions and allows for such functionality.

**Comment by BobRay** [comment]
If you do it early (around line 649 of the NP class file), you should be able to do this:

```
if ( isset($_GET['parentid'])) {
    $this->props['parentid'] = $_GET['parentid'];
}
```

**Comment by marcsch** [comment]
Thank you, but IMHO what you are proposing achieves the same as using the `getUrlParam` snippet, just in a different way. The problem occurs when trying to save the form: the parent ID is not forwarded to the postback page, and the `parentid` URL parameter is gone there, too, leading to an empty `parentid` property. Therefore, the new document will be saved as child of the NewsPublisher page.

For now, I worked around the problem by modifying the NP class file in a way that it forwards the parent id to the postback page through a hidden input.

**Comment by BobRay** [comment]
Can you post the code that does that?

I'm a little concerned about the security implications of letting any NP user set the parent of the doc they're creating by messing with $_POST array or a $_GET parameter.

**Comment by marcsch** [comment]
Oh, that code isn't sophisticated at all, more like a workaround. But here it is, replacing the lines 650-661:

```php

            if ($this->isPostBack) {
                $this->parentId = $_POST['np_parent_id'];

            } else {
                /* Convert legacy parent property */
                if (isset($this->props['parent'])) {
                    $this->props['parentid'] = $this->props['parent'];
                    unset($this->props['parent']);
                }
                $temp = $this->modx->getOption('parentid', $this->props, '');
                if (empty($temp)) {
                    $this->parentId = (int) $this->modx->resource->get('id');
                } else {
                    $this->parentId = is_numeric($temp)
                        ? (int) $temp
                        : $temp;
                }
             
            $stuff = '<input type="hidden" name="np_parent_id" value="' . $this->parentId . '" />';

            $this->modx->toPlaceholder('post_stuff', $stuff, $this->prefix);
 
```

In case you consider adding such a feature, it might be possible to store the parent ID as $_SESSION variable like in a similar way as the [document ID is stored by NpEditThisButton](https://github.com/BobRay/newspublisher/blob/master/core/components/newspublisher/elements/snippets/npeditthisbutton.snippet.php#L169) to prevent the user from messing around.

**Comment by BobRay** [comment]
I'm not quite following this. You don't appear to be accessing the $_GET array. Are you putting the the 'np_parent_id' in a form value before forwarding to NP so it will be in the $_POST array, and also setting the 'hid_submit' $_POST field in the form so it will appear to be a postback on the first pass? Or am I just confused?

**Comment by marcsch** [comment]
Sorry, the above code is only meant to propagate the parentid option to the postback page. It is specified as described in the first post: `&parentid='[[!getUrlParam?name='parentid']]'`. That's why I don't think it is a clean solution at all.
