### ISSUE TITLE
non-richtext fields

### ISSUE THREAD

**Issue by marcsch** [BobRay/newspublisher#48]
As far as I understand, textarea fields have a richtext editor activated by default. However, I cannot turn it off using snippet properties (maybe using property sets?). The cause seems to be that `$this->props` is not considered (e.g. line 1224 for introtext field).
Changing the code to this makes things work again.
`$rtSummary = (bool) $this->modx->getOption('rtsummary', $this->props, true);`

**Comment by BobRay** [comment]
&rtsummary=`0` should turn off the richtext for the introtext field (line 1230). Does it not?

**Comment by marcsch** [comment]
No, it didn't when I tested, unless I did something wrong. I believe that this affects the '[rtcontent](https://github.com/BobRay/newspublisher/blob/master/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1190)', '[rtdescription](https://github.com/BobRay/newspublisher/blob/master/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1214)' and '[rtsummary](https://github.com/BobRay/newspublisher/blob/master/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L1224)' properties.

**Comment by BobRay** [comment]
I was not able to replicate this. I was able to turn off rich text for the description and introtext fields.

I did find that it wasn't possible to turn off rich text for the content field if &initrte =`1`. It's assumed that if it you initialize the rte, you want rich text for the content field. You can turn it off, though, by removing the #np-content selector in the TinyMCEInit Tpl chunk.

**Comment by marcsch** [comment]
Strangely enough, I'm not able to reproduce my own issue any more. I'm not sure why this occurred. Therefore closing it and apologizing.

**Comment by BobRay** [comment]
I'm glad it sorted itself out.  It may have been a cache issue or maybe I fixed it and forgot. ;)
