### ISSUE TITLE
Call to a member function addJavascript() on a non-object 

### ISSUE THREAD

**Issue by garytube** [BobRay/newspublisher#50]
Hi Bob,

I installed NP 3.0.4 on MODx 2.5.7 and get this error:
`Fatal error: Call to a member function addJavascript() on a non-object in /home/uniquecpanel/public_html/core/components/tinymcerte/model/tinymcerte/events/tinymcerteonrichtexteditorinit.class.php on line 21`+

tinymcerteonrichtexteditorinit.class.php on line 21:
` $this->modx->controller->addJavascript($this->tinymcerte->getOption('jsUrl') . 'vendor/tinymce/tinymce.min.js');`

I used NP on different Sites before and had no issue. I belive the wrong tinymce is called, but I thought  since NP 3.0.x+ tinymce get loaded via CDN.

**Comment by garytube** [comment]
to temporary fix it, I uninstalled the TinyMCE Rich Text Editor 1.2.0 package

**Comment by BobRay** [comment]
I'm not sure what to say. That bug is exactly why I created the new version, which does load TinyMCE 4 via CDN. I've never seen that error, and I don't know why that class code would ever be executing in the front end, unless the old version of TinyMCE is set to load automatically on every request (maybe it's listed in the extension_packages System Settings?)

**Comment by garytube** [comment]
Do you maybe have a hint where to look? Like I said is used NP before and never had that issue with my setups.  I dig around and try to find something

**Comment by garytube** [comment]
i did a reinstall of NP, noticed the error...
`[Resource Resolver] Could not find parent: NewsPublisher
[Resource Resolver] Could not find parent: NewsPublisher
Setting template field for NewsPublisherEditor policy
Setting template_group for NewsPublisherPolicyTemplate
Package "newspublisher-3.0.4-pl" erfolgreich installiert.`

**Comment by BobRay** [comment]
Did you change the name of the NewsPublisher page or its alias?  That could explain the error messages during the install.  

As for the original error, it's coming from the code of the old TinyMCE file which NewsPublisher never loads.  One thing to try is to comment out this line (around line 833) in the core/components/newspublisher/model/newspublisher/newspublisher.class.php file:

`$this->modx->invokeEvent('OnRichTextEditorInit', $fields);`

Change it to:

` // $this->modx->invokeEvent('OnRichTextEditorInit', $fields);`

**Comment by janice171** [comment]
I'm getting the same error with an install on Modx 3.0.3 pl and NP 3.1.4.
```
[Resource Resolver] Could not find parent: NewsPublisher
[Resource Resolver] Could not find parent: NewsPublisher
Setting template field for NewsPublisherEditor policy
Successfully installed package newspublisher-3.1.4-pl
```
Also the only resources to be created are 'npElFinderConnector' and 'npElFinderFinder'. Nothing in the error logs.
Any ideas?

**Comment by BobRay** [comment]
Working on it, but I can't even get the NP package to install on MODX 3.0.3. The tabs on the first install screen are all blank (license, readme, etc.). Nothing in the error log. Did you install NP first, then upgrade MODX?

**Comment by janice171** [comment]
No this is on a new install of 3.0.3. Same on a Modx Cloud new install. Does NP work on previous v3's?

**Comment by BobRay** [comment]
Yes, I tested it on 3.0.1.  I don't know why it won't install for me on 3.0.3, but try this workaround:

Create a resource with the pagetitle NewsPublisher and the alias newspublisher, with this content:

`[[!NewsPublisher]]`

Make sure you have a Login page with the pagetitle Login and the alias login with this content:

`[[!Login]]`

Then reinstall NewsPublisher in Package Manager.

**Comment by janice171** [comment]
Thanks @BobRay that seems to work and display a 'create resource' form

**Comment by BobRay** [comment]
Thanks. I'm working on a new release of NewsPublisher.

Also, MODX 3.0.3 has a bug that affects Package Manager, it should be fixed soon.

**Comment by BobRay** [comment]
I believe the new release fixes this -- closing
