### ISSUE TITLE
Wish for choice for included js and css

### ISSUE THREAD

**Issue by alipang** [BobRay/newspublisher#52]
Most people probably love loading the javascript and css from CDN. I really don't like feeding Google with data they can use to "extend my user experience". With all their tentacles, resources and knowledge, they are in a great position to do amazing things with big data. So if I could choose to load from my own site, I would feel I'm not helping them.

And would it be possible to choose how and where to include js and css? I already have jquery at the end of my template, concatenated by cssSweet with the rest of my js.

**Comment by BobRay** [comment]
I think this is solved in the current version. Closing.
