### ISSUE TITLE
Custom Validation and Processing

### ISSUE THREAD

**Issue by matdave** [BobRay/newspublisher#55]
It would be nice to have options for custom validation or post hooks for special handling of fields. E.g. formatting text or validating the values before sending the save request.

**Comment by BobRay** [comment]
It's unlikely that I'll get to that any time soon, but it wouldn't be too difficult to do it with JavaScript attached to the Submit button.

**Comment by BobRay** [comment]
I think I'll leave custom JS solutions as the way to do this.
