### ISSUE TITLE
elFinder CSS windows-10 theme

### ISSUE THREAD

**Issue by mrhaw** [BobRay/newspublisher#58]
Not sure if I should report it here, but here goes

When loading the windows-10 css theme, I get a 404 on **home.png**

windows-10/css/toolbar.css has on line 85:
` .elfinder .elfinder-toolbar .elfinder-buttonset .elfinder-button-icon-home {
    background-image: url('../images/16px/home.png');`

The home.png should be **root.png**

See https://github.com/lokothodida/elfinder-theme-windows-10/blob/master/windows-10/css/toolbar.css
https://github.com/lokothodida/elfinder-theme-windows-10/blob/master/windows-10/images/16px/root.png
(I don't know who's github account that is)

As I was dealing with this I noticed more icons were missing and added to the image folder.
So I copied over the updated toolbar.css and all icons from here: 
https://github.com/lokothodida/elfinder-theme-windows-10/tree/master/windows-10/images/16px

**Comment by BobRay** [comment]
I think this is fixed in the current version. Let me know if not.
