### ISSUE TITLE
Wish: Possibility to insert Chunks between Form fields or use a master template for better structuring

### ISSUE THREAD

**Issue by frischnetz** [BobRay/newspublisher#59]
I use NewsPublisher a lot and it works very well. But it's not without problems. Most of my grievances could be solved if it was possible to insert custom chunks in between the form field blocks. At the moment I resort to using JS to enter stuff between the different inputs and I twist the CSS to conform to my wishes but it's a lot of hassle and it's not the MODX way of doing things.

There are two ways I can think of to alleviate the pain: either by using a master TEMPLATE for the form fields or by having the possibility to insert custom CHUNKs inbetween the form field blocks.

### TEMPLATE-solution (not the page template!)

The user would provide a ```&tpl=`MyTemplateChunk` ``` in the Newspublisher-Options. This Chunk would have to have placeholders for every TV-form-block (that are usually wrapped in a ```<div id="np-TVNAME-container">``` and could look like that:
```
<h3>personal information</h3>

[[+np-name-placeholder]]
[[+np-firstname-placeholder]]
[[+np-age-placeholder]]

<hr>

[[+np-position-placeholder]]

<h3>Company information</h3>

<p>Aenean posuere, tortor sed cursus feugiat, 
nunc augue blandit nunc, eu sollicitudin urna <p>

[[+np-companyname-placeholder]]
```
… and so on. This template would then be rendered between the `<form>` tags.

### CHUNK-solution

One would need to put all the extra HTML in separate CHUNKS and supply them in the snippet-options something like this:

```
[[!NewsPublisher?
	&show=`name, firstname, CHUNK-chunkname1, 
	age, CHUNK-chunkname2, position, 
	CHUNK-chunkname3, companyname, …`
	…
]]
```
here, chunknames (identified by the CHUNK-prefix) are inserted in the TV-list.

Or something like this:

```
[[!NewsPublisher?
	&show=`name, firstname, age, position, companyname, …`
	&chunks=`chunk1, void, void, void, chunk2, chunk3, chunk4, …`
	…
]]
```
where chunk1 would be 
```
<h3>personal information</h3>
```
chunk2 would be 
```
<hr>
```
and so on.

Here the chunks that are insert before the next TV-form-block would be listed in a separate option. `void` could be a keyword for not inserting a chunk at this position or just an empty/undefinded chunk.

I'm sure there are a lot of better solutions for this problem, but this is just a suggestion. Something like that would be immensely helpful to create forms that are better visually structured and easier to understand for the person entering the data.

What do you think?

**Comment by BobRay** [comment]
I'm not sure I understand you. Are these just blocks of text, or are they
input fields?

**Comment by frischnetz** [comment]
Hi Bob,

I'm sorry, I made it more confusing than necessary by suggesting two mutually exclusive possible solution to my goal.

My goal is to be more flexible in the design of the form pages: I want to be able to insert HTML and text between the form fields provided by NewsPublisher. I have long NP-pages where longer instructions, headlines and separators for the person entering data is needed. (I don't want to mess with the form fields themselves.)

This could be archieved by two (completely different) ways: 

1. Having a template for the whole form page (where I would need to enter some placeholders for the usual NP-Formfields. Between those placeholders I could enter my text and structuring elements.)

OR

2. Having a list of chunks defined that the NP-snippet would need to paste into the form page. My code or text would be in the chunks. So the NP-Snippet would create the form by alternating between pasting a form field and one of my chunks from the list.

Hope that I could clear it up a bit. I don't know if any of these suggestions are feasible or if you have a better idea how to be able to build better form fields. Would love to hear from you!

**Comment by BobRay** [comment]
Thanks, it makes sense to me now. It's a very good idea. Unfortunately, I have no time to work on it right now. I'll keep it in mind for the future.

**Comment by BobRay** [comment]
Quick question: Did you want NP to do any processing of the chunks (like setting placeholders), or can they just be inserted as-is at the point they appear in the &show list?

**Comment by BobRay** [comment]
Try [this commit](https://github.com/BobRay/newspublisher/commit/b3b4a8c576cef54a364ff448ab1665bb87d19a7d). Or just grab the newspublisher.class.php file. Be sure you're on the develop branch.  Just put the naked chunk names in the &show property where you want them to appear -- (no prefix).

**Comment by frischnetz** [comment]
I replaced `newspublisher.class.php` from 3.1.4 in my installation with this file and tried it with a simple new Chunk. I put the name with commas between two TVs in the &show-option. Unfortunately I get only a complaint about a missing TV (np_no_tv) and no form. I also tried to set ```&stopOnBadTv=`0` ``` but it did not have any effect. 

So I dug a bit. The problem was that even after the chunk was added to the output we still call `_displayTv` which then throws an error.

So I rearranged it and placed a `continue` after the chunk was added to the output so that `_displayTv` is not called after a chunk was found. (showing my lines 1052 to 1067:
```
            } else {
              
                /* See if it's a chunk */
                $chunk = $this->modx->getChunk($field);
                if (! empty ($chunk)) {
                    $inner .= "\n" . $chunk;
                    continue;
                }

                /* see if it's a TV */
                /* (presets done inside  _displayTv() ) */
                $retVal = $this->_displayTv($field);
                if ($retVal) {
                    $inner .= "\n" . $retVal;
                }
            }

```
Maybe another if-then would be better? At least this works for me now. Thanks so much!

**Comment by frischnetz** [comment]
The only thing that bothers my in this solution is that TV names and chunk names could collide which usually would (and should) be of no concern in MODX. Maybe prefixing them in `&show` would be a safer solution in the future?

**Comment by BobRay** [comment]
The logical thing would be to prefix them with $. I don't think that would interfere with any of the other code, but I'll have think about it. (And the $ would have to be removed before calling getChunk()).

**Comment by BobRay** [comment]
Try this with the $prefix:

                /* See if it's a chunk */
                if ($field[0] === '$') {
                    $chunk = $this->modx->getChunk(substr($field, 1));
                    if (!empty ($chunk)) {
                        $inner .= "\n" . $chunk;
                        continue;
                    }
                }

The continue statement really shouldn't be necessary, since it would be the last statement in the foreach loop, which would continue without it.

**Comment by frischnetz** [comment]
Yes, this works! Good solution! Thank you!

Will this be in the next release of NP, soon?

**Comment by BobRay** [comment]
Good question. I'll have to try to find the time to update the docs and do the release. I'm swamped right now.

**Comment by frischnetz** [comment]
OK. Don't worry! And thanks for the nice solution. It helps a lot!

**Comment by frischnetz** [comment]
I want to open this issue again because the code that is used in the latest version 3.1.5 does not work. The order of the test for a chunk (beginning with a $) needs to come first, otherwise it assumes it's a tv and complains that it's not found.

Lines 1049-1069 need to be like this:
```
            if (in_array($field,$resourceFieldNames)) {
                /* regular resource field */
                $inner .= $this->_displayField($field);
            } else {

                /* See if it's a chunk */
                if ($field[0] === '$') {
                    $chunk = $this->modx->getChunk(substr($field, 1));
                    if (!empty ($chunk)) {
                        $inner .= "\n" . $chunk;
                        continue;
                    }
                }

                /* see if it's a TV */
                /* (presets done inside  _displayTv() ) */
                $retVal = $this->_displayTv($field);
                if ($retVal) {
                    $inner .= "\n" . $retVal;
                }
            }
```

**Comment by frischnetz** [comment]
Just saw that you changed the code accordingly. This issue can be closed finally.
